import { afterEach, describe, expect, it, vi } from 'vitest'
import { resolveEnqueueInput } from '../lib/title-generator.js'
import * as composerLlmClient from '../planetz/composer-llm-client.js'

describe('resolveEnqueueInput', () => {
  afterEach(() => {
    vi.restoreAllMocks()
  })

  it('rejects when body is empty', async () => {
    await expect(resolveEnqueueInput({ body: '   ' })).rejects.toThrow('Task body is required')
  })

  it('rejects when body has only zero-width characters', async () => {
    await expect(resolveEnqueueInput({ body: '\u200B\u200C\u200D\u2060\uFEFF' })).rejects.toThrow(
      'Task body is required',
    )
  })

  it('normalizes explicit title and does not call orbit llm', async () => {
    const orbitSpy = vi.spyOn(composerLlmClient, 'callOrbitProviderRaw')
    const out = await resolveEnqueueInput(
      {
        title: '  Hello\nWorld  ',
        body: 'body',
        workflow: 'default',
      },
      { provider: 'mock', cwd: '/tmp/ws' },
    )
    expect(out.title).toBe('Hello World')
    expect(orbitSpy).not.toHaveBeenCalled()
  })

  it('uses orbit llm-generated title when available', async () => {
    vi.spyOn(composerLlmClient, 'callOrbitProviderRaw').mockResolvedValue('Generated by LLM')
    const out = await resolveEnqueueInput(
      { body: 'Need title', workflow: 'default' },
      { provider: 'mock', cwd: '/tmp/ws' },
    )
    expect(out.title).toBe('Generated by LLM')
  })

  it('falls back to first line when orbit llm is unavailable', async () => {
    const out = await resolveEnqueueInput({
      body: 'First line title\nSecond line details',
      workflow: 'default',
    })
    expect(out.title).toBe('First line title')
  })

  it('falls back to first line when orbit llm context is missing', async () => {
    vi.spyOn(composerLlmClient, 'callOrbitProviderRaw').mockRejectedValue(new Error('no provider'))
    const out = await resolveEnqueueInput(
      { body: 'First line title\nSecond line details', workflow: 'default' },
      { provider: 'mock', cwd: '/tmp/ws' },
    )
    expect(out.title).toBe('First line title')
  })

  it('falls back to timestamp when first line normalizes empty', async () => {
    vi.useFakeTimers()
    try {
      const now = new Date('2026-05-24T10:11:00Z')
      vi.setSystemTime(now)
      const pad = (n: number) => n.toString().padStart(2, '0')
      const expected = `task-${now.getFullYear()}${pad(now.getMonth() + 1)}${pad(now.getDate())}-${pad(
        now.getHours(),
      )}${pad(now.getMinutes())}`
      const out = await resolveEnqueueInput({
        body: '\u0000\u0001\nnext line',
        workflow: 'default',
      })
      expect(out.title).toBe(expected)
    } finally {
      vi.useRealTimers()
    }
  })

  it('passes through provider and model for IPC', async () => {
    const out = await resolveEnqueueInput({
      title: 'T',
      body: 'body text',
      workflow: 'default',
      provider: 'mock',
      model: 'mock-model',
    })
    expect(out.provider).toBe('mock')
    expect(out.model).toBe('mock-model')
  })
})
