import { IPC_CHANNELS } from './ipc-channels.js'

/** How preload maps bridge args to ipcRenderer.invoke payload. */
export type BridgeArgStyle =
  | 'none'
  | 'input'
  | 'optionalInput'
  | 'bootstrapStatus'
  | 'chainBranch'
  | 'selectTaskId'

export type BridgeManifestEntry =
  | { kind: 'event'; method: 'onStateUpdate'; channel: typeof IPC_CHANNELS.stateUpdate }
  | {
      kind: 'event'
      method: 'onComposerSessionStream'
      channel: typeof IPC_CHANNELS.composerSessionStream
    }
  | { kind: 'event'; method: 'onUiFocusTask'; channel: typeof IPC_CHANNELS.uiFocusTask }
  | {
      kind: 'invoke'
      method: string
      channel: string
      argStyle: BridgeArgStyle
      /** When true, main IPC handler calls broadcastAfterMutation. */
      broadcasts: boolean
    }

export const BRIDGE_EVENT_ENTRIES = [
  {
    kind: 'event',
    method: 'onStateUpdate',
    channel: IPC_CHANNELS.stateUpdate,
  },
  {
    kind: 'event',
    method: 'onComposerSessionStream',
    channel: IPC_CHANNELS.composerSessionStream,
  },
  {
    kind: 'event',
    method: 'onUiFocusTask',
    channel: IPC_CHANNELS.uiFocusTask,
  },
] as const

export const BRIDGE_EVENT_METHODS = BRIDGE_EVENT_ENTRIES.map((entry) => entry.method)

/** @deprecated Use BRIDGE_EVENT_ENTRIES */
export const BRIDGE_EVENT_ENTRY = BRIDGE_EVENT_ENTRIES[0]

/** Invoke entries: preload wiring and check:bridge sync (v1; OrbitBridge signatures stay hand-written). */
export const BRIDGE_INVOKE_MANIFEST = [
  {
    kind: 'invoke',
    method: 'selectWorkspace',
    channel: IPC_CHANNELS.workspaceSelect,
    argStyle: 'none',
    broadcasts: true,
  },
  {
    kind: 'invoke',
    method: 'getWorkspace',
    channel: IPC_CHANNELS.workspaceGet,
    argStyle: 'none',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'getWorkspaceCurrentGitBranch',
    channel: IPC_CHANNELS.workspaceCurrentGitBranch,
    argStyle: 'none',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'listWorkspaceGitBranches',
    channel: IPC_CHANNELS.workspaceGitBranches,
    argStyle: 'none',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'listRecentWorkspaces',
    channel: IPC_CHANNELS.workspaceListRecent,
    argStyle: 'none',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'openRecentWorkspace',
    channel: IPC_CHANNELS.workspaceOpenRecent,
    argStyle: 'input',
    broadcasts: true,
  },
  {
    kind: 'invoke',
    method: 'removeRecentWorkspace',
    channel: IPC_CHANNELS.workspaceRemoveRecent,
    argStyle: 'input',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'setBootstrapStatus',
    channel: IPC_CHANNELS.workspaceSetBootstrap,
    argStyle: 'bootstrapStatus',
    broadcasts: true,
  },
  {
    kind: 'invoke',
    method: 'getDesktopCapabilities',
    channel: IPC_CHANNELS.desktopGetCapabilities,
    argStyle: 'none',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'enqueueTask',
    channel: IPC_CHANNELS.taskEnqueue,
    argStyle: 'input',
    broadcasts: true,
  },
  {
    kind: 'invoke',
    method: 'retryTask',
    channel: IPC_CHANNELS.taskRetry,
    argStyle: 'input',
    broadcasts: true,
  },
  {
    kind: 'invoke',
    method: 'resumeTask',
    channel: IPC_CHANNELS.taskResume,
    argStyle: 'input',
    broadcasts: true,
  },
  {
    kind: 'invoke',
    method: 'stopTask',
    channel: IPC_CHANNELS.taskStop,
    argStyle: 'input',
    broadcasts: true,
  },
  {
    kind: 'invoke',
    method: 'resumeStoppedTask',
    channel: IPC_CHANNELS.taskResumeStopped,
    argStyle: 'input',
    broadcasts: true,
  },
  {
    kind: 'invoke',
    method: 'reviseTask',
    channel: IPC_CHANNELS.taskRevise,
    argStyle: 'input',
    broadcasts: true,
  },
  {
    kind: 'invoke',
    method: 'deleteTask',
    channel: IPC_CHANNELS.taskDelete,
    argStyle: 'input',
    broadcasts: true,
  },
  {
    kind: 'invoke',
    method: 'runTaskNow',
    channel: IPC_CHANNELS.taskRunNow,
    argStyle: 'input',
    broadcasts: true,
  },
  {
    kind: 'invoke',
    method: 'runPendingTask',
    channel: IPC_CHANNELS.taskRunPending,
    argStyle: 'input',
    broadcasts: true,
  },
  {
    kind: 'invoke',
    method: 'openTaskWorkDir',
    channel: IPC_CHANNELS.taskOpenWorkDir,
    argStyle: 'input',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'openTaskResultPath',
    channel: IPC_CHANNELS.taskOpenResultPath,
    argStyle: 'input',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'listConversationsForTask',
    channel: IPC_CHANNELS.conversationListForTask,
    argStyle: 'input',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'listConversationHistory',
    channel: IPC_CHANNELS.conversationHistoryList,
    argStyle: 'optionalInput',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'getConversationHistory',
    channel: IPC_CHANNELS.conversationHistoryGet,
    argStyle: 'input',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'deleteConversationHistory',
    channel: IPC_CHANNELS.conversationHistoryDelete,
    argStyle: 'input',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'searchConversationHistory',
    channel: IPC_CHANNELS.conversationHistorySearch,
    argStyle: 'input',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'getChatComposerDraft',
    channel: IPC_CHANNELS.chatComposerDraftGet,
    argStyle: 'none',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'saveChatComposerDraft',
    channel: IPC_CHANNELS.chatComposerDraftSave,
    argStyle: 'input',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'getChatSessionPendingChanges',
    channel: IPC_CHANNELS.chatSessionGetPendingChanges,
    argStyle: 'input',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'getChatSessionPendingChangeFile',
    channel: IPC_CHANNELS.chatSessionGetPendingChangeFile,
    argStyle: 'input',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'applyChatSessionChanges',
    channel: IPC_CHANNELS.chatSessionApplyChanges,
    argStyle: 'input',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'listChatMcpPendingConsent',
    channel: IPC_CHANNELS.chatMcpListPendingConsent,
    argStyle: 'none',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'grantChatMcpConsent',
    channel: IPC_CHANNELS.chatMcpGrantConsent,
    argStyle: 'input',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'listChatMcpServersOverview',
    channel: IPC_CHANNELS.chatMcpListServersOverview,
    argStyle: 'none',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'setChatMcpSecret',
    channel: IPC_CHANNELS.chatMcpSetSecret,
    argStyle: 'input',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'recordChatToTaskMetric',
    channel: IPC_CHANNELS.chatToTaskMetricRecord,
    argStyle: 'input',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'getTaskResult',
    channel: IPC_CHANNELS.taskGetResult,
    argStyle: 'input',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'startComposerSession',
    channel: IPC_CHANNELS.composerSessionStart,
    argStyle: 'input',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'getActiveComposerSession',
    channel: IPC_CHANNELS.composerSessionGetActive,
    argStyle: 'none',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'getComposerAssistCapabilities',
    channel: IPC_CHANNELS.composerSessionGetCapabilities,
    argStyle: 'none',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'resumeComposerSession',
    channel: IPC_CHANNELS.composerSessionResume,
    argStyle: 'input',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'messageComposerSession',
    channel: IPC_CHANNELS.composerSessionMessage,
    argStyle: 'input',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'finalizeComposerSession',
    channel: IPC_CHANNELS.composerSessionFinalize,
    argStyle: 'input',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'acceptComposerSession',
    channel: IPC_CHANNELS.composerSessionAccept,
    argStyle: 'input',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'playComposerSession',
    channel: IPC_CHANNELS.composerSessionPlay,
    argStyle: 'input',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'buildComposerSourceContext',
    channel: IPC_CHANNELS.composerSessionBuildSourceContext,
    argStyle: 'input',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'cancelComposerSession',
    channel: IPC_CHANNELS.composerSessionCancel,
    argStyle: 'input',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'interruptComposerSession',
    channel: IPC_CHANNELS.composerSessionInterrupt,
    argStyle: 'input',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'listTaskResultDiff',
    channel: IPC_CHANNELS.resultDiffSummary,
    argStyle: 'input',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'getTaskResultDiffFile',
    channel: IPC_CHANNELS.resultDiffFile,
    argStyle: 'input',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'mergeResult',
    channel: IPC_CHANNELS.resultMerge,
    argStyle: 'input',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'createResultPr',
    channel: IPC_CHANNELS.resultCreatePr,
    argStyle: 'input',
    broadcasts: true,
  },
  {
    kind: 'invoke',
    method: 'checkResultBranch',
    channel: IPC_CHANNELS.resultCheckBranch,
    argStyle: 'input',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'initializeWorkspace',
    channel: IPC_CHANNELS.workspaceInitialize,
    argStyle: 'input',
    broadcasts: true,
  },
  {
    kind: 'invoke',
    method: 'startWatch',
    channel: IPC_CHANNELS.watchStart,
    argStyle: 'none',
    broadcasts: true,
  },
  {
    kind: 'invoke',
    method: 'stopWatch',
    channel: IPC_CHANNELS.watchStop,
    argStyle: 'none',
    broadcasts: true,
  },
  {
    kind: 'invoke',
    method: 'listPromptHistory',
    channel: IPC_CHANNELS.promptHistoryList,
    argStyle: 'optionalInput',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'deletePromptHistoryItem',
    channel: IPC_CHANNELS.promptHistoryDelete,
    argStyle: 'input',
    broadcasts: true,
  },
  {
    kind: 'invoke',
    method: 'getWorkflowPreview',
    channel: IPC_CHANNELS.workflowGetPreview,
    argStyle: 'input',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'previewWorkflowAutoRoute',
    channel: IPC_CHANNELS.workflowPreviewAutoRoute,
    argStyle: 'input',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'swapTaskWorkflow',
    channel: IPC_CHANNELS.taskSwapWorkflow,
    argStyle: 'input',
    broadcasts: true,
  },
  {
    kind: 'invoke',
    method: 'listWorkflows',
    channel: IPC_CHANNELS.workflowList,
    argStyle: 'none',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'readWorkflow',
    channel: IPC_CHANNELS.workflowRead,
    argStyle: 'input',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'readWorkflowFacets',
    channel: IPC_CHANNELS.workflowReadFacets,
    argStyle: 'input',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'listWorkflowBuiltinFacets',
    channel: IPC_CHANNELS.workflowListBuiltinFacets,
    argStyle: 'none',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'listProjectFacets',
    channel: IPC_CHANNELS.facetListProject,
    argStyle: 'none',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'readFacet',
    channel: IPC_CHANNELS.facetRead,
    argStyle: 'input',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'writeProjectFacet',
    channel: IPC_CHANNELS.facetWriteProject,
    argStyle: 'input',
    broadcasts: true,
  },
  {
    kind: 'invoke',
    method: 'deleteProjectFacet',
    channel: IPC_CHANNELS.facetDeleteProject,
    argStyle: 'input',
    broadcasts: true,
  },
  {
    kind: 'invoke',
    method: 'listFacetUsages',
    channel: IPC_CHANNELS.facetListUsages,
    argStyle: 'input',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'writeProjectWorkflow',
    channel: IPC_CHANNELS.workflowWriteProject,
    argStyle: 'input',
    broadcasts: true,
  },
  {
    kind: 'invoke',
    method: 'installSpecDrivenWorkflow',
    channel: IPC_CHANNELS.workflowInstallSpecDriven,
    argStyle: 'none',
    broadcasts: true,
  },
  {
    kind: 'invoke',
    method: 'validateWorkflow',
    channel: IPC_CHANNELS.workflowValidate,
    argStyle: 'input',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'pickWorkflowImportYaml',
    channel: IPC_CHANNELS.workflowPickImportYaml,
    argStyle: 'none',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'saveWorkflowDraft',
    channel: IPC_CHANNELS.workflowDraftSave,
    argStyle: 'input',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'loadWorkflowDraft',
    channel: IPC_CHANNELS.workflowDraftLoad,
    argStyle: 'input',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'deleteWorkflowDraft',
    channel: IPC_CHANNELS.workflowDraftDelete,
    argStyle: 'input',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'createChainTask',
    channel: IPC_CHANNELS.chainCreate,
    argStyle: 'input',
    broadcasts: true,
  },
  {
    kind: 'invoke',
    method: 'materializeChainEdge',
    channel: IPC_CHANNELS.chainMaterialize,
    argStyle: 'input',
    broadcasts: true,
  },
  {
    kind: 'invoke',
    method: 'checkChainSourceBranch',
    channel: IPC_CHANNELS.chainCheckBranch,
    argStyle: 'chainBranch',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'deleteChain',
    channel: IPC_CHANNELS.chainDelete,
    argStyle: 'input',
    broadcasts: true,
  },
  {
    kind: 'invoke',
    method: 'setChainEdgeStatus',
    channel: IPC_CHANNELS.chainSetEdgeStatus,
    argStyle: 'input',
    broadcasts: true,
  },
  {
    kind: 'invoke',
    method: 'toggleHookServer',
    channel: IPC_CHANNELS.integrationsToggleHookServer,
    argStyle: 'input',
    broadcasts: true,
  },
  {
    kind: 'invoke',
    method: 'toggleAdapter',
    channel: IPC_CHANNELS.integrationsToggleAdapter,
    argStyle: 'input',
    broadcasts: true,
  },
  {
    kind: 'invoke',
    method: 'pushExternalAgent',
    channel: IPC_CHANNELS.integrationsPushExternal,
    argStyle: 'input',
    broadcasts: true,
  },
  {
    kind: 'invoke',
    method: 'selectTask',
    channel: IPC_CHANNELS.uiSelectTask,
    argStyle: 'selectTaskId',
    broadcasts: true,
  },
  {
    kind: 'invoke',
    method: 'getConnectionStatus',
    channel: IPC_CHANNELS.connectionGetStatus,
    argStyle: 'none',
    broadcasts: true,
  },
  {
    kind: 'invoke',
    method: 'getSettings',
    channel: IPC_CHANNELS.settingsGet,
    argStyle: 'none',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'updateSettings',
    channel: IPC_CHANNELS.settingsUpdate,
    argStyle: 'input',
    broadcasts: true,
  },
  {
    kind: 'invoke',
    method: 'getEngineConfig',
    channel: IPC_CHANNELS.engineConfigGet,
    argStyle: 'none',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'getAgentOverrides',
    channel: IPC_CHANNELS.agentOverridesGet,
    argStyle: 'none',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'updateAgentOverrides',
    channel: IPC_CHANNELS.agentOverridesUpdate,
    argStyle: 'input',
    broadcasts: true,
  },
  {
    kind: 'invoke',
    method: 'openYaml',
    channel: IPC_CHANNELS.yamlOpen,
    argStyle: 'input',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'listExecutionCatalog',
    channel: IPC_CHANNELS.executionCatalogList,
    argStyle: 'none',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'listProviderModels',
    channel: IPC_CHANNELS.providerModelsList,
    argStyle: 'input',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'rememberProviderModelSelection',
    channel: IPC_CHANNELS.providerModelSelectionRemember,
    argStyle: 'input',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'listModelHistory',
    channel: IPC_CHANNELS.modelHistoryList,
    argStyle: 'optionalInput',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'deleteModelHistoryItem',
    channel: IPC_CHANNELS.modelHistoryDelete,
    argStyle: 'input',
    broadcasts: true,
  },
  {
    kind: 'invoke',
    method: 'listProviderEfforts',
    channel: IPC_CHANNELS.providerEffortsList,
    argStyle: 'input',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'listEffortHistory',
    channel: IPC_CHANNELS.effortHistoryList,
    argStyle: 'optionalInput',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'deleteEffortHistoryItem',
    channel: IPC_CHANNELS.effortHistoryDelete,
    argStyle: 'input',
    broadcasts: true,
  },
  {
    kind: 'invoke',
    method: 'updateEngineConfig',
    channel: IPC_CHANNELS.engineConfigUpdate,
    argStyle: 'input',
    broadcasts: true,
  },
  {
    kind: 'invoke',
    method: 'importEngineConfigFromTakt',
    channel: IPC_CHANNELS.engineConfigImportFromTakt,
    argStyle: 'optionalInput',
    broadcasts: true,
  },
  {
    kind: 'invoke',
    method: 'importGlobalTaktFromHome',
    channel: IPC_CHANNELS.taktGlobalImportFromHome,
    argStyle: 'optionalInput',
    broadcasts: true,
  },
  {
    kind: 'invoke',
    method: 'importWorkflowFromTakt',
    channel: IPC_CHANNELS.workflowImportFromTakt,
    argStyle: 'input',
    broadcasts: true,
  },
  {
    kind: 'invoke',
    method: 'confirmCanonicalImport',
    channel: IPC_CHANNELS.canonicalImportConfirm,
    argStyle: 'optionalInput',
    broadcasts: true,
  },
  {
    kind: 'invoke',
    method: 'dismissCanonicalImport',
    channel: IPC_CHANNELS.canonicalImportDismiss,
    argStyle: 'none',
    broadcasts: true,
  },
  {
    kind: 'invoke',
    method: 'listExecutionLog',
    channel: IPC_CHANNELS.executionLogList,
    argStyle: 'optionalInput',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'getExecutionSummary',
    channel: IPC_CHANNELS.executionSummaryGet,
    argStyle: 'optionalInput',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'listPendingIntentLedger',
    channel: IPC_CHANNELS.intentLedgerListPending,
    argStyle: 'optionalInput',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'countPendingIntentLedger',
    channel: IPC_CHANNELS.intentLedgerCountPending,
    argStyle: 'optionalInput',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'getIntentLedgerSummary',
    channel: IPC_CHANNELS.intentLedgerGetSummary,
    argStyle: 'optionalInput',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'listIntentLedgerByThread',
    channel: IPC_CHANNELS.intentLedgerListByThread,
    argStyle: 'input',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'listSupplyIntentLedger',
    channel: IPC_CHANNELS.intentLedgerListSupply,
    argStyle: 'none',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'getCurrentDecidedIntent',
    channel: IPC_CHANNELS.decidedIntentGetCurrent,
    argStyle: 'input',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'listDecidedIntentVersions',
    channel: IPC_CHANNELS.decidedIntentListVersions,
    argStyle: 'input',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'saveDecidedIntent',
    channel: IPC_CHANNELS.decidedIntentSave,
    argStyle: 'input',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'getIntentDraft',
    channel: IPC_CHANNELS.intentDraftGet,
    argStyle: 'input',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'saveIntentDraft',
    channel: IPC_CHANNELS.intentDraftSave,
    argStyle: 'input',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'generateIntentDraft',
    channel: IPC_CHANNELS.intentDraftGenerate,
    argStyle: 'input',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'clearIntentDraft',
    channel: IPC_CHANNELS.intentDraftClear,
    argStyle: 'input',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'listSpecThreadSummaries',
    channel: IPC_CHANNELS.specThreadSummaryList,
    argStyle: 'optionalInput',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'getValidationCoverageSummary',
    channel: IPC_CHANNELS.validationCoverageGetSummary,
    argStyle: 'none',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'ratifyIntentLedgerEntry',
    channel: IPC_CHANNELS.intentLedgerRatify,
    argStyle: 'input',
    broadcasts: true,
  },
  {
    kind: 'invoke',
    method: 'reverseIntentLedgerEntry',
    channel: IPC_CHANNELS.intentLedgerReverse,
    argStyle: 'input',
    broadcasts: true,
  },
  {
    kind: 'invoke',
    method: 'adoptIntentLedgerEntry',
    channel: IPC_CHANNELS.intentLedgerAdopt,
    argStyle: 'input',
    broadcasts: true,
  },
  {
    kind: 'invoke',
    method: 'fixIntentLedgerEntry',
    channel: IPC_CHANNELS.intentLedgerFix,
    argStyle: 'input',
    broadcasts: true,
  },
  {
    kind: 'invoke',
    method: 'listKiroSpecs',
    channel: IPC_CHANNELS.kiroSpecList,
    argStyle: 'none',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'getKiroSpec',
    channel: IPC_CHANNELS.kiroSpecGet,
    argStyle: 'input',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'getOllamaHealth',
    channel: IPC_CHANNELS.ollamaHealthGet,
    argStyle: 'optionalInput',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'previewOllamaExecutionGuard',
    channel: IPC_CHANNELS.ollamaExecutionGuardPreview,
    argStyle: 'input',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'pullOllamaModel',
    channel: IPC_CHANNELS.ollamaModelPull,
    argStyle: 'input',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'deleteOllamaModel',
    channel: IPC_CHANNELS.ollamaModelDelete,
    argStyle: 'input',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'listOpenGitHubIssues',
    channel: IPC_CHANNELS.githubIssueListOpen,
    argStyle: 'optionalInput',
    broadcasts: false,
  },
  {
    kind: 'invoke',
    method: 'fetchGitHubIssue',
    channel: IPC_CHANNELS.githubIssueFetch,
    argStyle: 'input',
    broadcasts: false,
  },
] as const

export const BRIDGE_MANIFEST = [BRIDGE_EVENT_ENTRY, ...BRIDGE_INVOKE_MANIFEST] as const

export type BridgeInvokeMethodName = (typeof BRIDGE_INVOKE_MANIFEST)[number]['method']

/** Invoke slice of OrbitBridge wired from BRIDGE_INVOKE_MANIFEST (preload typing aid). */
export type BridgeInvokeSlice = Pick<
  import('./bridge-types.js').OrbitBridge,
  BridgeInvokeMethodName
>
